name: fluttersaurus
description: A Flutter thesaurus made for Byteconf Flutter 2020.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.4 <4.0.0"

dependencies:
  bloc: ^9.1.0
  bloc_concurrency: ^0.3.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  stream_transform: ^2.0.0
  thesaurus_repository:
    path: packages/thesaurus_repository

dev_dependencies:
  bloc_lint: ^0.3.2
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
