name: fluttersaurus
description: A Flutter thesaurus made for Byteconf Flutter 2020.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  google_fonts: ^4.0.5
  shimmer: ^2.0.0
  stream_transform: ^2.0.0
  thesaurus_repository:
    path: packages/thesaurus_repository

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
