name: thesaurus_repository
description: A Dart package for the thesaurus domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  datamuse_api:
    path: ../datamuse_api
