name: datamuse_api
description: A Dart API Client for the Datamuse API.
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  http: ^1.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  bloc_lint: ^0.3.2
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
